name: Roadmap Item
description: Report a feature request / major task / Minor work item
title: "[TYPE] "
labels: []
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Feature
        - Major Task
        - Minor Work
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What needs to be done and why?
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done?
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Links, screenshots, related issues, dependencies.
